{
  "success": false,
  "return_code": 1,
  "stdout": "",
  "stderr": "Traceback (most recent call last):\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v2/07_24_2025/backtests_final/VolumePulseBreakout_BTFinal_v1.py\", line 129, in <module>\n    stats = bt.run()\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/backtesting.py\", line 1139, in run\n    strategy.init()\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v2/07_24_2025/backtests_final/VolumePulseBreakout_BTFinal_v1.py\", line 31, in init\n    self.equity = 1000000\nAttributeError: can't set attribute 'equity'\n\nERROR conda.cli.main_run:execute(124): `conda run python /Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v2/07_24_2025/backtests_final/VolumePulseBreakout_BTFinal_v1.py` failed. (See above for error)\n",
  "execution_time": 1.127917,
  "timestamp": "2025-07-24T11:38:23.495672"
}