{
  "success": false,
  "return_code": 1,
  "stdout": "",
  "stderr": "Traceback (most recent call last):\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v3/10_20_2025/backtests_final/AdaptiveDivergence_BTFinal_v5.py\", line 299, in <module>\n    stats = bt.run()\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/backtesting.py\", line 1139, in run\n    strategy.init()\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v3/10_20_2025/backtests_final/AdaptiveDivergence_BTFinal_v5.py\", line 60, in init\n    print(f\"\ud83c\udf19 AdaptiveDivergence initialized! \ud83d\ude80 Initial cash: {self._broker.cash:,} \u2728\")\nAttributeError: '_Broker' object has no attribute 'cash'. Did you mean: '_cash'?\n\nERROR conda.cli.main_run:execute(124): `conda run python /Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v3/10_20_2025/backtests_final/AdaptiveDivergence_BTFinal_v5.py` failed. (See above for error)\n",
  "execution_time": 1.148643,
  "timestamp": "2025-10-20T10:28:31.499570"
}