{
  "success": false,
  "return_code": 1,
  "stdout": "",
  "stderr": "Traceback (most recent call last):\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v3/10_20_2025/backtests_optimized/ExtremeDivergence_OPT_v9.py\", line 140, in <module>\n    stats = bt.run()\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/backtesting.py\", line 1170, in run\n    strategy.next()\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v3/10_20_2025/backtests_optimized/ExtremeDivergence_OPT_v9.py\", line 51, in next\n    price_slice_low = self.data.Low[:current_len].values\nAttributeError: '_Array' object has no attribute 'values'\n\nERROR conda.cli.main_run:execute(124): `conda run python /Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v3/10_20_2025/backtests_optimized/ExtremeDivergence_OPT_v9.py` failed. (See above for error)\n",
  "execution_time": 1.380537,
  "timestamp": "2025-10-20T10:22:03.331139"
}