{
  "success": false,
  "return_code": 1,
  "stdout": "\ud83c\udf19 Moon Dev Backtest Initialized: InverseMomentum Strategy Loaded! \u2728\n\ud83c\udf19 Moon Dev Debug [50]: Fast SMA 24498.38, Slow SMA 24268.07, Vol 9733 vs Avg 14364, Close 24281.31 vs Trend 23072.47 \ud83d\ude80\n\ud83c\udf19 Moon Dev Entry: Bullish momentum on BTC! Crossover confirmed with volume & trend. Entry: 24184.44, Size: 0.39999999999999997, SL: 22975.22 \ud83d\ude80\n\n",
  "stderr": "Traceback (most recent call last):\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v3/10_20_2025/backtests_package/InverseMomentum_PKG.py\", line 90, in <module>\n    stats = bt.run()\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/backtesting.py\", line 1165, in run\n    broker.next()\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/backtesting.py\", line 765, in next\n    self._process_orders()\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/backtesting.py\", line 902, in _process_orders\n    self._open_trade(adjusted_price, need_size, order.sl, order.tp, time_index)\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/backtesting.py\", line 970, in _open_trade\n    trade.sl = sl\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/backtesting.py\", line 636, in sl\n    self.__set_contingent('sl', price)\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/backtesting.py\", line 655, in __set_contingent\n    assert price is None or 0 < price < np.inf\nAssertionError\n\nERROR conda.cli.main_run:execute(124): `conda run python /Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v3/10_20_2025/backtests_package/InverseMomentum_PKG.py` failed. (See above for error)\n",
  "execution_time": 1.042941,
  "timestamp": "2025-10-20T10:34:55.833993"
}