{
  "success": false,
  "return_code": 1,
  "stdout": "",
  "stderr": "/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/test/__init__.py:8: FutureWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.\n  return pd.read_csv(join(dirname(__file__), filename),\n/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/test/__init__.py:8: FutureWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.\n  return pd.read_csv(join(dirname(__file__), filename),\nTraceback (most recent call last):\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi/03_14_2025/research/GPT-5/DeltaSentiment_BT.py\", line 48, in <module>\n    data.columns = ['Open', 'High', 'Low', 'Close', 'Volume']\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/pandas/core/generic.py\", line 6218, in __setattr__\n    return object.__setattr__(self, name, value)\n  File \"properties.pyx\", line 69, in pandas._libs.properties.AxisProperty.__set__\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/pandas/core/generic.py\", line 767, in _set_axis\n    self._mgr.set_axis(axis, labels)\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/pandas/core/internals/managers.py\", line 227, in set_axis\n    self._validate_set_axis(axis, new_labels)\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/pandas/core/internals/base.py\", line 85, in _validate_set_axis\n    raise ValueError(\nValueError: Length mismatch: Expected axis has 6 elements, new values have 5 elements\n\nERROR conda.cli.main_run:execute(124): `conda run python /Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi/03_14_2025/research/GPT-5/DeltaSentiment_BT.py` failed. (See above for error)\n",
  "execution_time": 3.093112,
  "timestamp": "2025-08-08T12:43:57.775527"
}