{
  "success": false,
  "return_code": 1,
  "stdout": "",
  "stderr": "Traceback (most recent call last):\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v2/10_20_2025/backtests_final/ShadowSpread_BTFinal_v3.py\", line 101, in <module>\n    stats = bt.run()\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/backtesting.py\", line 1170, in run\n    strategy.next()\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v2/10_20_2025/backtests_final/ShadowSpread_BTFinal_v3.py\", line 56, in next\n    if self._i % 100 == 0:\nAttributeError: 'ShadowSpread' object has no attribute '_i'\n\nERROR conda.cli.main_run:execute(124): `conda run python /Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v2/10_20_2025/backtests_final/ShadowSpread_BTFinal_v3.py` failed. (See above for error)\n",
  "execution_time": 1.019113,
  "timestamp": "2025-10-20T09:20:56.449249"
}